export const GET_FIVE_DAY_BY_ZIP_PENDING = 'GET_FIVE_DAY_BY_ZIP_PENDING'
export const GET_FIVE_DAY_BY_ZIP_SUCCESS = 'GET_FIVE_DAY_BY_ZIP_SUCCESS'
export const GET_FIVE_DAY_BY_ZIP_FAILED = 'GET_FIVE_DAY_BY_ZIP_FAILED'

export const GET_FIVE_DAY_BY_CITY_PENDING = 'GET_FIVE_DAY_BY_CITY_PENDING'
export const GET_FIVE_DAY_BY_CITY_SUCCESS = 'GET_FIVE_DAY_BY_CITY_SUCCESS'
export const GET_FIVE_DAY_BY_CITY_FAILED = 'GET_FIVE_DAY_BY_CITY_FAILED'